//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIS
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    public partial class Datum : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
    	protected virtual void OnPropertyChanged(string propertyName)
    	{
    			PropertyChangedEventHandler handler = PropertyChanged;
    			if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
    	}
    private System.DateTime _date;
        public System.DateTime Date { get { return _date; } set { _date = value; OnPropertyChanged("Date");} }
    private int _id;
        public int Id { get { return _id; } set { _id = value; OnPropertyChanged("Id");} }
    private int _strijker1_id;
        public int Strijker1_ID { get { return _strijker1_id; } set { _strijker1_id = value; OnPropertyChanged("Strijker1_ID");} }
    private Nullable<int> _strijker2_id;
        public Nullable<int> Strijker2_ID { get { return _strijker2_id; } set { _strijker2_id = value; OnPropertyChanged("Strijker2_ID");} }
    private Nullable<int> _strijker3_id;
        public Nullable<int> Strijker3_ID { get { return _strijker3_id; } set { _strijker3_id = value; OnPropertyChanged("Strijker3_ID");} }
    private Nullable<int> _strijker4_id;
        public Nullable<int> Strijker4_ID { get { return _strijker4_id; } set { _strijker4_id = value; OnPropertyChanged("Strijker4_ID");} }
    private Nullable<int> _strijker5_id;
        public Nullable<int> Strijker5_ID { get { return _strijker5_id; } set { _strijker5_id = value; OnPropertyChanged("Strijker5_ID");} }
    
        public virtual Strijker Strijker1 { get; set; }
        public virtual Strijker Strijker2 { get; set; }
        public virtual Strijker Strijker3 { get; set; }
        public virtual Strijker Strijker4 { get; set; }
        public virtual Strijker Strijker5 { get; set; }
        public virtual Prestatie Prestaties { get; set; }
    }
}
