//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISIS_DataEntities : DbContext
    {
        public ISIS_DataEntities()
            : base("name=ISIS_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Strijker> Strijkers { get; set; }
        public virtual DbSet<Klant> Klanten { get; set; }
        public virtual DbSet<Prestatie> Prestaties { get; set; }
        public virtual DbSet<Winkel> Winkels { get; set; }
        public virtual DbSet<School> Scholen { get; set; }
        public virtual DbSet<Bedrijf> Bedrijven { get; set; }
        public virtual DbSet<Ophaling> Ophalingen { get; set; }
    }
}
