//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Klanten : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private int _id;
        public int ID {
            get { return _id; }
            set {
                _id = value;
                OnPropertyChanged("ID"); 
            }
        }

        private string _gebruikersnummer;
        public string Gebruikersnummer
        {
            get { return _gebruikersnummer; }
            set { _gebruikersnummer = value; OnPropertyChanged("Gebruikersnummer"); }
        }

        private string _naam;
        public string Naam
        {
            get { return _naam; }
            set
            {
                _naam = value;
                OnPropertyChanged("Naam");
            }
        }

        private string _voornaam;
        public string Voornaam {
            get
            {
                return _voornaam;
            }
            set
            {                    
                _voornaam = value;
                OnPropertyChanged("Voornaam");
            }
        }
        private string _straat;
        public string Straat { get { return _straat; } set { _straat = value; OnPropertyChanged("Straat"); } }
        private Nullable<int> _nummer;
        public Nullable<int> Nummer { get { return _nummer; } set { _nummer = value; OnPropertyChanged("Nummer"); } }
        private Nullable<int> _postcode;
        public Nullable<int> Postcode { get { return _postcode; } set { _postcode = value; OnPropertyChanged("Postcode"); } }
        private string _gemeente;
        public string Gemeente { get { return _gemeente; } set { _gemeente = value; OnPropertyChanged("Gemeente"); } }
        private string _telefoon;
        public string Telefoon { get { return _telefoon; } set { _telefoon = value; OnPropertyChanged("Telefoon"); } }
        private string _gsm;
        public string Gsm { get { return _gsm; } set { _gsm = value; OnPropertyChanged("Gsm"); } }
        private string _email;
        public string Email { get { return _email; } set { _email = value; OnPropertyChanged("Email"); } }
        private string _anderenaam;
        public string AndereNaam { get { return _anderenaam; } set { _anderenaam = value; OnPropertyChanged("AndereNaam"); } }
        private string _betalingswijze;
        public string Betalingswijze { get { return _betalingswijze; } set { _betalingswijze = value; OnPropertyChanged("Betalingswijze"); } }
        private string _soortklant;
        public string SoortKlant { get { return _soortklant; } set { _soortklant = value; OnPropertyChanged("SoortKlant"); } }
        private Nullable<int> _actief;
        public Nullable<int> Actief { get { return _actief; } set { _actief = value; OnPropertyChanged("Actief"); } }
        private Nullable<int> _strijkbox;
        public Nullable<int> Strijkbox { get { return _strijkbox; } set { _strijkbox = value; OnPropertyChanged("Strijkbox"); } }
        private Nullable<int> _waarborg;
        public Nullable<int> Waarborg { get { return _waarborg; } set { _waarborg = value; OnPropertyChanged("Waarborg"); } }
        private string _bericht;
        public string Bericht { get { return _bericht; } set { _bericht = value; OnPropertyChanged("Bericht"); } }
        private Nullable<System.DateTime> _datum;
        public Nullable<System.DateTime> Datum { get { return _datum; } set { _datum = value; OnPropertyChanged("Datum"); } }
        private Nullable<System.DateTime> _laatsteactiviteit;
        public Nullable<System.DateTime> LaatsteActiviteit { get { return _laatsteactiviteit; } set { _laatsteactiviteit = value; OnPropertyChanged("LaatsteActiviteit"); } }       
    }
}
