//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stijkers
    {
        public long ID { get; set; }
        public string Naam { get; set; }
        public string Straat { get; set; }
        public Nullable<long> Nummer { get; set; }
        public Nullable<long> Postcode { get; set; }
        public string Gemeente { get; set; }
        public string Telefoon { get; set; }
        public string Gsm { get; set; }
        public string RSZ { get; set; }
        public string Actief { get; set; }
        public string Nota { get; set; }
        public string Voornaam { get; set; }
        public string LaatsteWijziging { get; set; }
    }
}
