//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIS
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    public partial class Strijkers : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
    	protected virtual void OnPropertyChanged(string propertyName)
    	{
    			PropertyChangedEventHandler handler = PropertyChanged;
    			if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
    	}
    private int _id;
        public int ID { get { return _id; } set { _id = value; OnPropertyChanged("ID");} }
    private string _naam;
        public string Naam { get { return _naam; } set { _naam = value; OnPropertyChanged("Naam");} }
    private string _adres;
        public string Adres { get { return _adres; } set { _adres = value; OnPropertyChanged("Adres");} }
    private Nullable<int> _nummer;
        public Nullable<int> Nummer { get { return _nummer; } set { _nummer = value; OnPropertyChanged("Nummer");} }
    private Nullable<int> _postcode;
        public Nullable<int> Postcode { get { return _postcode; } set { _postcode = value; OnPropertyChanged("Postcode");} }
    private string _gemeente;
        public string Gemeente { get { return _gemeente; } set { _gemeente = value; OnPropertyChanged("Gemeente");} }
    private Nullable<int> _tel;
        public Nullable<int> Tel { get { return _tel; } set { _tel = value; OnPropertyChanged("Tel");} }
    private string _rsz;
        public string RSZ { get { return _rsz; } set { _rsz = value; OnPropertyChanged("RSZ");} }
    private string _actief;
        public string Actief { get { return _actief; } set { _actief = value; OnPropertyChanged("Actief");} }
    private string _laatstewijziging;
        public string LaatsteWijziging { get { return _laatstewijziging; } set { _laatstewijziging = value; OnPropertyChanged("LaatsteWijziging");} }
    private string _nota;
        public string Nota { get { return _nota; } set { _nota = value; OnPropertyChanged("Nota");} }
    }
}
