//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIS
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    public partial class Strijkers : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
    	protected virtual void OnPropertyChanged(string propertyName)
    	{
    			PropertyChangedEventHandler handler = PropertyChanged;
    			if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
    	}
    private int _id;
        public int ID { get { return _id; } set { _id = value; OnPropertyChanged("ID");} }
    private string _naam;
        public string Naam { get { return _naam; } set { _naam = value; OnPropertyChanged("Naam");} }
    private string _adres;
        public string Adres { get { return _adres; } set { _adres = value; OnPropertyChanged("Adres");} }
    private Nullable<int> _nummer;
        public Nullable<int> Nummer { get { return _nummer; } set { _nummer = value; OnPropertyChanged("Nummer");} }
    private Nullable<int> _postcode;
        public Nullable<int> Postcode { get { return _postcode; } set { _postcode = value; OnPropertyChanged("Postcode");} }
    private string _gemeente;
        public string Gemeente { get { return _gemeente; } set { _gemeente = value; OnPropertyChanged("Gemeente");} }
    private Nullable<int> _tel;
        public Nullable<int> Tel { get { return _tel; } set { _tel = value; OnPropertyChanged("Tel");} }
    private string _rnsz;
        public string RNSZ { get { return _rnsz; } set { _rnsz = value; OnPropertyChanged("RNSZ");} }
    private string _login;
        public string Login { get { return _login; } set { _login = value; OnPropertyChanged("Login");} }
    private string _bankrekening;
        public string Bankrekening { get { return _bankrekening; } set { _bankrekening = value; OnPropertyChanged("Bankrekening");} }
    private Nullable<System.DateTime> _indienstvanaf;
        public Nullable<System.DateTime> IndienstVanaf { get { return _indienstvanaf; } set { _indienstvanaf = value; OnPropertyChanged("IndienstVanaf");} }
    private string _email;
        public string Email { get { return _email; } set { _email = value; OnPropertyChanged("Email");} }
    private Nullable<int> _urentewerkstelling;
        public Nullable<int> UrenTewerkstelling { get { return _urentewerkstelling; } set { _urentewerkstelling = value; OnPropertyChanged("UrenTewerkstelling");} }
    }
}
