// <auto-generated />
namespace EF_Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Strijker_IndienstTot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Strijker_IndienstTot));
        
        string IMigrationMetadata.Id
        {
            get { return "201603082030262_Strijker_IndienstTot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
