// <auto-generated />
namespace EF_Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StrijkerVoornaam_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StrijkerVoornaam_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "201602052215087_StrijkerVoornaam_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
