// <auto-generated />
namespace EF_Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Datum_RenamedIdToPrestatieId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Datum_RenamedIdToPrestatieId));
        
        string IMigrationMetadata.Id
        {
            get { return "201602051242323_Datum_RenamedIdToPrestatieId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
